/**
 * Pre-configured market templates for MVP
 */

export const defaultMarkets = [
  {
    id: 1,
    name: 'Taiwan',
    regulatoryAuthority: 'TFDA',
    language: 'zh-TW',
    script: 'Traditional Chinese',
    requiredSections: [
      'Product Name',
      'Composition',
      'Indications',
      'Dosage and Administration',
      'Contraindications',
      'Warnings and Precautions',
      'Adverse Reactions',
      'Drug Interactions',
      'Use in Special Populations',
      'Overdosage',
      'Pharmacological Properties',
      'Pharmaceutical Particulars',
      'Storage',
      'Packaging',
      'Manufacturer Information',
      'Marketing Authorization Holder',
      'Date of Revision'
    ],
    sectionOrdering: {
      'Product Name': 1,
      'Composition': 2,
      'Indications': 3,
      'Dosage and Administration': 4,
      'Contraindications': 5,
      'Warnings and Precautions': 6,
      'Adverse Reactions': 7,
      'Drug Interactions': 8,
      'Use in Special Populations': 9,
      'Overdosage': 10,
      'Pharmacological Properties': 11,
      'Pharmaceutical Particulars': 12,
      'Storage': 13,
      'Packaging': 14,
      'Manufacturer Information': 15,
      'Marketing Authorization Holder': 16,
      'Date of Revision': 17
    },
    extractionProviderPreference: 'GoogleDocAI',
    formattingRules: {
      dateFormat: 'YYYY/MM/DD',
      measurementUnits: 'metric',
      emergencyContacts: 'TFDA Drug Safety Hotline: 02-2787-8200',
      mandatoryDisclaimers: [
        '本藥須由醫師處方使用',
        '請詳閱說明書並遵醫囑使用'
      ]
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 2,
    name: 'Thailand',
    regulatoryAuthority: 'Thai FDA',
    language: 'th',
    script: 'Thai',
    requiredSections: [
      'Product Name',
      'Qualitative and Quantitative Composition',
      'Pharmaceutical Form',
      'Clinical Particulars',
      'Therapeutic Indications',
      'Posology and Method of Administration',
      'Contraindications',
      'Special Warnings and Precautions for Use',
      'Interaction with Other Medicinal Products',
      'Pregnancy and Lactation',
      'Effects on Ability to Drive',
      'Undesirable Effects',
      'Overdose',
      'Pharmacological Properties',
      'Pharmaceutical Particulars',
      'Storage Conditions',
      'Nature and Contents of Container',
      'Marketing Authorization Holder',
      'Date of Revision'
    ],
    sectionOrdering: {
      'Product Name': 1,
      'Qualitative and Quantitative Composition': 2,
      'Pharmaceutical Form': 3,
      'Clinical Particulars': 4,
      'Therapeutic Indications': 5,
      'Posology and Method of Administration': 6,
      'Contraindications': 7,
      'Special Warnings and Precautions for Use': 8,
      'Interaction with Other Medicinal Products': 9,
      'Pregnancy and Lactation': 10,
      'Effects on Ability to Drive': 11,
      'Undesirable Effects': 12,
      'Overdose': 13,
      'Pharmacological Properties': 14,
      'Pharmaceutical Particulars': 15,
      'Storage Conditions': 16,
      'Nature and Contents of Container': 17,
      'Marketing Authorization Holder': 18,
      'Date of Revision': 19
    },
    extractionProviderPreference: 'GoogleDocAI',
    formattingRules: {
      dateFormat: 'DD/MM/YYYY',
      measurementUnits: 'metric',
      emergencyContacts: 'Thai FDA Hotline: 1556',
      mandatoryDisclaimers: [
        'ยานี้ต้องใช้ตามใบสั่งแพทย์',
        'โปรดอ่านเอกสารกำกับยาและปฏิบัติตามคำแนะนำของแพทย์'
      ]
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 3,
    name: 'Vietnam',
    regulatoryAuthority: 'DAV',
    language: 'vi',
    script: 'Vietnamese',
    requiredSections: [
      'Product Name',
      'Composition',
      'Pharmaceutical Form',
      'Indications',
      'Dosage and Administration',
      'Contraindications',
      'Warnings and Precautions',
      'Drug Interactions',
      'Adverse Reactions',
      'Use in Pregnancy and Lactation',
      'Effects on Driving',
      'Overdose',
      'Pharmacodynamics',
      'Pharmacokinetics',
      'Storage',
      'Packaging',
      'Shelf Life',
      'Manufacturer',
      'Marketing Authorization Holder',
      'Date of Revision'
    ],
    sectionOrdering: {
      'Product Name': 1,
      'Composition': 2,
      'Pharmaceutical Form': 3,
      'Indications': 4,
      'Dosage and Administration': 5,
      'Contraindications': 6,
      'Warnings and Precautions': 7,
      'Drug Interactions': 8,
      'Adverse Reactions': 9,
      'Use in Pregnancy and Lactation': 10,
      'Effects on Driving': 11,
      'Overdose': 12,
      'Pharmacodynamics': 13,
      'Pharmacokinetics': 14,
      'Storage': 15,
      'Packaging': 16,
      'Shelf Life': 17,
      'Manufacturer': 18,
      'Marketing Authorization Holder': 19,
      'Date of Revision': 20
    },
    extractionProviderPreference: 'ClaudeVision',
    formattingRules: {
      dateFormat: 'DD/MM/YYYY',
      measurementUnits: 'metric',
      emergencyContacts: 'DAV Hotline: 1900-6767',
      mandatoryDisclaimers: [
        'Thuốc này chỉ được sử dụng theo đơn của bác sĩ',
        'Đọc kỹ hướng dẫn sử dụng trước khi dùng'
      ]
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 4,
    name: 'Korea',
    regulatoryAuthority: 'KFDA',
    language: 'ko',
    script: 'Korean',
    requiredSections: [
      'Product Name',
      'Composition',
      'Indications',
      'Dosage and Administration',
      'Contraindications',
      'Warnings',
      'Precautions',
      'Adverse Reactions',
      'Drug Interactions',
      'Use in Pregnancy and Lactation',
      'Pediatric Use',
      'Geriatric Use',
      'Overdosage',
      'Clinical Pharmacology',
      'Storage',
      'Packaging',
      'Manufacturer',
      'Distributor',
      'Date of Revision'
    ],
    sectionOrdering: {
      'Product Name': 1,
      'Composition': 2,
      'Indications': 3,
      'Dosage and Administration': 4,
      'Contraindications': 5,
      'Warnings': 6,
      'Precautions': 7,
      'Adverse Reactions': 8,
      'Drug Interactions': 9,
      'Use in Pregnancy and Lactation': 10,
      'Pediatric Use': 11,
      'Geriatric Use': 12,
      'Overdosage': 13,
      'Clinical Pharmacology': 14,
      'Storage': 15,
      'Packaging': 16,
      'Manufacturer': 17,
      'Distributor': 18,
      'Date of Revision': 19
    },
    extractionProviderPreference: 'GoogleDocAI',
    formattingRules: {
      dateFormat: 'YYYY.MM.DD',
      measurementUnits: 'metric',
      emergencyContacts: 'KFDA Consumer Hotline: 1577-1255',
      mandatoryDisclaimers: [
        '전문의약품',
        '의사의 처방에 따라 사용하십시오'
      ]
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }
];